### PR TITLE
feat(list-all): list versions from releases-index.json

### PR DESCRIPTION
**Pull request by spartanroger**
Using `tac` to return the list upside down, to focus on the latest versions.

### CODE REVIEW

**Comment by spartanroger** [comment]
That's weird, I use a Mac with Mojave 10.14.6. The problem I see with sort is that the main version (aka 3.0.0) is behind other less important versions (3.0.0-rc1). Do you know how to handle that ? I tried sort -V but didn't work. 


Example with `tac`:

```
1.0.0 1.0.1 1.0.2 1.0.3 1.0.4 1.0.5 1.0.7 1.0.8 1.0.9 1.0.10 1.0.11 1.0.12 1.0.13 1.0.14 1.0.15 1.0.16 1.1.0 1.1.1 1.1.2 1.1.4 1.1.5 1.1.6 1.1.7 1.1.8 1.1.9 1.1.10 1.1.11 1.1.12 1.1.13 2.0.0-preview1 2.0.0-preview2 2.0.0 2.0.3 2.0.3 2.0.4 2.0.5 2.1.100 2.0.6 2.1.102 2.1.103 2.1.104 2.0.7 2.0.8 2.1.201 2.0.9 2.1.0-preview1 2.1.0-preview2 2.1.0-rc1 2.1.0 2.1.1 2.1.2 2.1.3 2.1.4 2.1.5 2.1.6 2.1.600-preview 2.1.502 2.1.7 2.1.8 2.1.9 2.1.602 2.1.10 2.1.603 2.1.11 2.1.604 2.1.700 2.1.12 2.1.801 2.1.13 2.2.0-preview1 2.2.0-preview2 2.2.0-preview3 2.2.0 2.2.200-preview 2.2.101 2.2.1 2.2.103 2.2.2 2.2.3 2.2.202 2.2.4 2.2.203 2.2.5 2.2.204 2.2.300 2.2.6 2.2.7 3.0.0-preview1 3.0.0-preview2 3.0.0-preview3 3.0.0-preview4 3.0.0-preview5 3.0.0-preview6 3.0.0-preview7 3.0.0-preview8 3.0.0-preview9 3.0.0-rc1 3.0.0
```

Example with `sort -V`:

```
1.0.0 1.0.1 1.0.10 1.0.11 1.0.12 1.0.13 1.0.14 1.0.15 1.0.16 1.0.2 1.0.3 1.0.4 1.0.5 1.0.7 1.0.8 1.0.9 1.1.0 1.1.1 1.1.10 1.1.11 1.1.12 1.1.13 1.1.2 1.1.4 1.1.5 1.1.6 1.1.7 1.1.8 1.1.9 2.0.0 2.0.0-preview1 2.0.0-preview2 2.0.3 2.0.3 2.0.4 2.0.5 2.0.6 2.0.7 2.0.8 2.0.9 2.1.0 2.1.0-preview1 2.1.0-preview2 2.1.0-rc1 2.1.1 2.1.10 2.1.100 2.1.102 2.1.103 2.1.104 2.1.11 2.1.12 2.1.13 2.1.2 2.1.201 2.1.3 2.1.4 2.1.5 2.1.502 2.1.6 2.1.600-preview 2.1.602 2.1.603 2.1.604 2.1.7 2.1.700 2.1.8 2.1.801 2.1.9 2.2.0 2.2.0-preview1 2.2.0-preview2 2.2.0-preview3 2.2.1 2.2.101 2.2.103 2.2.2 2.2.200-preview 2.2.202 2.2.203 2.2.204 2.2.3 2.2.300 2.2.4 2.2.5 2.2.6 2.2.7 3.0.0 3.0.0-preview1 3.0.0-preview2 3.0.0-preview3 3.0.0-preview4 3.0.0-preview5 3.0.0-preview6 3.0.0-preview7 3.0.0-preview8 3.0.0-preview9 3.0.0-rc1
```

**Comment by sebastian** [comment]
I tried running the `spartanroger:master`-version locally to get version 3.0.0 running on macOS Catalina, but I am seeing the following error:

```
$ asdf install dotnet-core 3.0.0
Downloading the CLI installer
Installing the CLI requested version 3.0.0. Please wait, installation may take a few minutes.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-sdk-3.0.0-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-sdk-3.0.0-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-dev-osx-x64.3.0.0.tar.gz
curl: (22) The requested URL returned error: 404
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-dev-osx-x64.3.0.0.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.0.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
The CLI has been installed.
```

**Comment by spartanroger** [comment]
@sebastian that's weird. I checked the requirements specified by asdf for the `list-all` command, and the tests have passed so I assumed everything was ok.

Could you explain the steps to reproduce this error? I'll try to understand what's happening. 

tks a lot

**Comment by sebastian** [comment]
@spartanroger, I'd be happy to try to help debug.
Firstly, I am running macOS Catalina (10.15 (19A583))

I have since downloaded and installed dotnet core 3.0 using the standard installer provided [directly by Microsoft](https://dotnet.microsoft.com/download). Could it be interfering? I did not have it installed when I first reported the problem.

Using the following steps I can reproduce the problem:

```
$ asdf plugin-remove dotnet-core
$ asdf plugin-add dotnet-core https://github.com/spartanroger/asdf-dotnet-core.git
$ asdf list-all dotnet-core
...
3.0.0-preview9
3.0.0-rc1
3.0.0
3.1.0-preview1
$ asdf install dotnet-core 3.0.0
Downloading the CLI installer
Installing the CLI requested version 3.0.0. Please wait, installation may take a few minutes.
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-sdk-3.0.0-osx-x64.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-sdk-3.0.0-osx-x64.tar.gz
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-dev-osx-x64.3.0.0.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.0/dotnet-dev-osx-x64.3.0.0.tar.gz
dotnet_install: Error: Could not find/download: `.NET Core SDK` with version = 3.0.0
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
The CLI has been installed.
```

**Pull request merged**
